env:
  DIGITAL_OCEAN_REGISTRY: registry.digitalocean.com/badcodeinc
  IMAGE_NAME: ${{ github.event.repository.name }}
name: Build and and publish docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_REGISTRY_PASSWORD }}
    - name: Build container image
      run: docker build -t ${{ env.DIGITAL_OCEAN_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ env.DIGITAL_OCEAN_REGISTRY }}/${{env.DIGITAL_OCEAN_REGISTRY}}:latest

