env:
  DIGITAL_OCEAN_REGISTRY: registry.digitalocean.com/badcodeinc
  IMAGE_NAME: ${{ github.event.repository.name }}
name: Build and and publish docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DigitalOcean Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DIGITAL_OCEAN_REGISTRY }}
        username: ${{ secrets.DIGITAL_OCEAN_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITAL_OCEAN_REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DIGITAL_OCEAN_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.DIGITAL_OCEAN_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.DIGITAL_OCEAN_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

